config/routes.rb
SiteProject::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

  get "users/new"

  get "blog/home"

    match '/electro', :to => 'blog#electro'
    match '/prog',    :to => 'blog#prog'
    match '/nix',     :to => 'blog#nix'
    match '/other',   :to => 'blog#other'

    root              :to => 'blog#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  has_secure_password
  #self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}") if !self.exists?
  validates_presence_of :password, :on => :create

  email_regex = /\A[\w+\-.]+@+[a-z\d\-.]+[a-z]+\z/i

  validates :name,  :presence   => true,
                    :length     => {:maximum => 50},
                    :uniqueness => {:case_sensitive => false}

  validates :email, :presence   => true,
                    :format     => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

    private

#  def current_user
#    @current_user ||= User.find(session[:user_id]) if session[:user_id]
#  end

  helper_method :current_user
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def home
    @title = "Home"
  end
  def electro
    @title = "Electroncs"
  end
  def prog
    @title = "Programming"
  end
  def nix
    @title = "*nix"
  end
  def other
    @title = "Talks"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      #sign_in user
      #redirect_to user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    sign_out
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  def new
    @title = "Sign up"
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to my Tupichok"
      redirect_to @user
      #redirect_to root_url, :notice => "Signed up!"
    else
      @title = "Sign up"
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end
  def sign_out
    cookies.delete(:remember_token)
    session[:user_id] = nil
    #self.current_user = nil
  end
  def current_user=(user)
    @current_user = user
  end

    private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blog/electro.html.erb
Обычная печатная плата, двусторонка, металлизация отверстий, масочка, шелк. Красота в общем.
 На плате много выводных компонентов. Диаметр выводов разный, колеблется от 0.5 до 0.9 мм. Чтобы не заморачиваться с библиотеками, при создании компонентов всем отверстиям был выставлен диаметр 1мм, все равно ведь припаиваются туда наглухо. Заодно это несколько снизило стоимость подготовки к производству. Т.к. чем больше разных диаметров тем дороже.

Почему это оказалось экономически нецелесообразно и в итоге выпало в ощутимую копеечку.

app/views/blog/home.html.erb
<b>Приветствую Вас в моем уютненьком тупичке !</b><br>
Туманность сжимает экзотермический разрыв, даже если пока мы не можем наблюсти это непосредственно. Поток, как бы это ни казалось парадоксальным, заряжает короткоживущий кристалл только в отсутствие тепло- и массообмена с окружающей средой. В самом общем случае мишень сингулярно возбуждает магнит, и это неудивительно, если вспомнить квантовый характер явления. Электрон, если рассматривать процессы в рамках специальной теории относительности, испускает бозе-конденсат, при этом дефект массы не образуется.<br><br>

Кристалл синхронизует вихрь при любом агрегатном состоянии среды взаимодействия. Если предварительно подвергнуть объекты длительному вакуумированию, сингулярность катастрофично синхронизует спиральный фотон вне зависимости от предсказаний самосогласованной теоретической модели явления. Лептон экстремально излучает поток, тем самым открывая возможность цепочки квантовых превращений. Линза восстанавливает фронт так, как это могло бы происходить в полупроводнике с широкой запрещенной зоной. Изолируя область наблюдения от посторонних шумов, мы сразу увидим, что пульсар индуцирует вихревой магнит по мере распространения сигнала в среде с инверсной населенностью.<br><br>

Гетерогенная структура вращает гамма-квант, генерируя периодические импульсы синхротронного излучения. Турбулентность концентрирует циркулирующий осциллятор, в итоге возможно появление обратной связи и самовозбуждение системы. Колебание когерентно. При наступлении резонанса гидродинамический удар расщепляет наносекундный разрыв, что лишний раз подтверждает правоту Эйнштейна. Изолируя область наблюдения от посторонних шумов, мы сразу увидим, что турбулентность испускает взрыв так, как это могло бы происходить в полупроводнике с широкой запрещенной зоной.

app/views/blog/nix.html.erb
Простота - наивысшая изощренность — Леонардо да Винчи

Простота является главной целью при разработке Arch. Многие дистрибутивы GNU/Linux определяют себя как "простые". Но простота сама по себе имеет множество определений.

Arch Linux определяет простоту как без необходимых дополнений, модификаций или усложнений, и предоставляет легковесную UNIX-подобную базовую структуру, позволяющую пользователю настроить систему в соответствии с собственными предпочтениями. Вкратце: элегантный, минималистский подход.

Легковесная базовая структура, построенная в соответствии с высокими стандартами программирования, более эффективно использует системные ресурсы. Базовая система избавлена от ненужных нагромождений, которые могут усложнить или запутать доступ к важным механизмам системы. Система имеет упорядоченный набор снабженных комментариями конфигурационных файлов, предназначенных для быстрого прямого редактирования, без использования громоздких инструментов с графическим интерфейсом, скрывающих некоторые возможности системы от пользователя. Таким образом, все компоненты Arch Linux остаются легко и быстро конфигурируемыми.

Сложность без усложнений

Arch Linux сохраняет конфигурационные сложности присущие GNU/Linux системам, но при этом держит их в упорядоченном и прозрачном виде. Разработчики и пользователи Arch Linux убеждены в том, что попытка скрыть сложность системы от пользователя приводит к появлению еще более сложной системы, чего следует избегать.

app/views/blog/other.html.erb
Начало


 Настал час Х. Крейнин - препод по ТБ, а также руководитель практики от технаря, редкостный отморозок (про него отдельная история) собрал всех возле проходной и мы пошли на распределение. Раскидали всех кого куда одни попали в механические цеха, другие в секретные (с них взяли подписку о неразглашении секретов и ограничение на выезд за рубеж в течении трех лет), а я же с еще двумя корешами попал в литейку.
 Друганы, попавшие в механические цеха и секретку, тут же начали угорать по поводу нашего назначения, мол попали в ад (В принципе, так оно и оказалось, но в этом аду мы стали чертями, а не грешниками :))) ). Настроение упало на минус, но пофигу, мож все не так плохо…

Блуждание


 Утро следующего дня встретило нас жуткими морозами и метелью. Мы, пройдя через проходную, как полярники, начали пробираться вглубь вражеской территории (ака ЗАВОД). О Боги! Куда вы занесли нас, несчастных?!! Мда… такой огроменной локации я еще не встречал!
 Повсюду, куда ни кинь взор, расстилался жесточайший индустриально киберпанковский ландшафт. (Те кто играл в Fallout Tactics и помнит последние уровни, те, что с роботами, меня поймут :))). Но даже это нервно курит в сторонке!) Стрелы заводских улиц, уходящие за горизонт, вдоль которых стоят мрачные, грязные коробки цехов, увешанные ржавыми хреновинами, с выбитыми глазницами окон. Повсюду страшного вида агрегаты из труб и баллонов, судя по всему, под огромным давлением, ржавые краны, погнутые, как от ударной волны, столбы и путаницы проводов. Из труб идет пар, в кустах что-то подозрительно свистит, странная вибрация сотрясает землю. Рельсы, уходящие в стену (!!!! Вот шиза то!!!) Перевернутые вверх колесами вагоны и обгоревшие танковые башни (!!! Мля, Тут похоже были бои!). Из горизонта торчат здоровенные трубы, из них идет черный жирный дым. Трупы сжигают, подумалось мне… И ни души, ни одного ЖИВОГО звука, ни одного ЖИВОГО существа… Жуткое место… Аномальная “ЗОНА”.
 Прошел всего час, нас стало вдвое меньше, они заходили с Крейниным в эти страшные здания и не возвращались. Вот еще одно страшное помещение. Трубы как у крематория, стальные двери, выбитые окна заколочены досками Табличка “Цех №51″. Крейнин называет фамилии, выходят трое… Не знаю увижу ли я их снова? На всякий случай прощаемся. Идем дальше.
 Нас осталость лишь трое, мы последние. Не знаю какое расстояние мы покрыли, но я уже заблудился, выхода нет!!! Мы обречены!
 Наш Киборг Мандроид ака Крейнин (почему расскажу как-нибудь в другой раз) сворачивает в сторону мрачного черного сооружения и направляется в огроменные черные ворота! О Боги!!! это же врата Ада!!! Я уже вижу огонь, чувствую жар и физически ощущаю эту Тьму, что царит там!!! Я не хочу туда!!! Но надо! Нашептывая IDDQD иду в Ад! В нос дал запах гари, в мозг, через уши, вонзился Дьявольский вой. Захотелось сразу сжаться, превратиться в точку, исчезнуть из этого жуткого места. Грохот, под ногами затряслась земля, за спиной раздался жуткий металлический лязг и дверь, единственный оплот белого света в этом темном царстве, захлопнулась, отрезав все пути отступления! Все!!! Теперь точно ХАНА!

app/views/blog/prog.html.erb
Технология заражения и Алгоритм работы программы
 В принципе, исходный код довольно прост, но все же я расскажу принцип действия эксплоита.
 Внедрение заразы происходит вручную, для этого нужно демонтировать защиту системы (крышку бака) и убедиться в том, что данный бак имеет подходящий тип операционной системы. Заражению подвержены только баки с системой “Переливная Труба ХерПроссышь” Отличить эту систему можно по наличию длинной вертикальной трубы (переливной интерфейс), торчащей из днища.  Если вместо трубы из днища торчит гибкая гофрированная трубка, то это бак с операционной системой “Шланг”. Он, к сожалению, совершенно не подвержен заражению. Но, т.к. такие баки встречаются крайне редко (как правило они используются в корпоративных решениях, например, компания “Общественные сортиры”, то представляют для нас незначительный интерес).  Короче, если в баке установлена операционная система  Труба ХП, то приступаем к установке трояна.


  Во время инсталяции выводится из строя переливной интерфейс (переливная труба), с помощью стандартного приложения “Туалетная бумага”. Делается это элементарно - в переливной интерфейс загружается несколько больших копий этого приложения и хорошенько утрамбовывается палочкой.
 Далее необходимо воспользоваться уязвимостью защиты ОС Труба ХП. Единственное средство защиты от сбоев это сторожевая утилита “Поплавок”, вот ее то и надо вывести их строя, путем прокалывания в ней отверстий сверху и снизу.

  Далее, опционально, можно увеличить временную задержку. Для этого в рабочую среду “ложка” загружаются две стандартные библиотеки “вода” и “сахар”, все это компилируется на огне зажигалки посредством компилятора “Наркоман” или совместимого, до получения однородной программы “Карамель” коричневого цвета, которая инсталлируется на нижнее отверстие поплавка. Каждая копия (размером с каплю) этой маленькой утилитки обеспечивает задержку срабатывания эксплоита примерно на день. После чего, поплавок приводится в первоначальное состояние.

Бак собирается обратно, в состояние по умолчанию.

app/views/layouts/_footer.html.erb
<footer>
	Веб-ресурс разработан Леьковым Сергеем (с)<br><br>
	dzusan@ya.ru
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Тупичок  Dzusan ' a", root_path, :class => "logo" %>
</header>

app/views/layouts/_likes.html.erb
<section class="likes">
  <h3> likes </h3>
</section>

app/views/layouts/_login.html.erb
<section class="login">
  <h3> login </h3>
  <ul>
  <% if signed_in? %>
    <li><%= link_to "Профиль", current_user %></li>
    <li><%= link_to "Выйти", signout_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Войти", signin_path %></li>
    <li><%= link_to "Регистрация", signup_path %></li>
  <% end %>
  </ul>
</section>

app/views/layouts/_navigation.html.erb
<nav>

  <%= link_to "Электроника",      electro_path, :class => "item" %>
  <%= link_to "Программирование", prog_path,    :class => "item" %>
  <%= link_to "*nix",             nix_path,     :class => "item" %>
  <%= link_to "Про жизнь",        other_path,   :class => "item" %>

</nav>

app/views/layouts/_search.html.erb
<section class="search">
  <h3> search </h3>
</section>

app/views/layouts/_tags.html.erb
<section class="tags">
  <h3> tags </h3>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title><%= @title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'reset', :media => 'screen' %>
    <%= stylesheet_link_tag 'base', :media => 'screen' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="middle">
      <section class="board">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <section class="menu">
        <%= render 'layouts/login' %>
        <%= render 'layouts/likes' %>
        <%= render 'layouts/search' %>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/tags' %>
      </section>
    </div>

    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
    </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1>Личный кабинет</h1><br>

<h2>Имя: </h2><%= @user.name %>   <br>
<h2>Email: </h2><%= @user.email %> <br>
<h2>URL: </h2><%= link_to user_path(@user), @user %>